<?php

/**
 * ProcessPreview
 *
 * By Nico Knoll (http://www.nico-knoll.de/)
 *
 */

class ProcessPreview extends Process implements Module {

	public static function getModuleInfo() {
		return array(
			'title' => 'Preview', 
			'version' => '2.00', 
			'summary' => 'Let you see a preview of a page.',
			'singular' => true, 
			'autoload' => true 
		);
	}

	public function init() {
		parent::init();
		$this->addHook('ProcessPageEdit::buildForm', $this, 'addButton');
		$this->addHook('ProcessPageEdit::execute', $this, 'addButtonJavascript');
		$this->addHook('ProcessPageView::execute', $this, 'changeView');
	}
	
	
	public function changeView(HookEvent $event) {		
		if($this->page->template != 'admin' && wire('user')->isLoggedin() && $_POST) {
			$page = $this->page;
			unset($_POST['preview_save'], $_POST['name'], $_POST['parent_id'], $_POST['status']);
			
			foreach($_POST as $key => $value) {
				$page->setFieldValue($key, $value);
			}
			
			$page->status = Page::statusOn;
			
			$event->return = $page->render();
		}
	}


	public function addButton(HookEvent $event) {
		$this->config->styles->add($this->config->urls->ProcessPreview.'ProcessPreview.css');
		
		$field = $this->modules->get('InputfieldSubmit');
		$field->attr('id+name', 'preview'); 
		$field->attr('class', $field->class); 
		$field->attr('value', 'Preview'); 

		$event->return = $event->return->append($field); 
	}

	public function addButtonJavascript(HookEvent $event) {
		$page = $this->pages->get($_GET['id']);
		$js = '<script type="text/javascript">
		var preview = false;
		$("#wrap_preview").click(function() {
			preview = true;
		});

		$("#ProcessPageEdit").submit(function() {
			if(preview == true) {
				$.ajax({
				  type: "POST",
				  url: "'.$page->url.'",
				  data: $(this).serialize(),
				  success: function(data){
					var win = window.open("about:blank");
					with(win.document) {
					  open();
					  write(data);
					  close();
					}
				  }
				});
				return false;
			}
		});
		

		</script>';
		$event->return = $event->return.$js;
	}
}
